//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Combate"",
            ""id"": ""3d0fe0e3-b83c-434c-b806-e8215cc305ac"",
            ""actions"": [
                {
                    ""name"": ""Ataque"",
                    ""type"": ""Button"",
                    ""id"": ""9b988acc-a09a-4ec8-9a91-108c12394f11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""93e51c6c-62ad-4355-9ad0-c2eaede5d078"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Ataque"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Combate
        m_Combate = asset.FindActionMap("Combate", throwIfNotFound: true);
        m_Combate_Ataque = m_Combate.FindAction("Ataque", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Combate
    private readonly InputActionMap m_Combate;
    private List<ICombateActions> m_CombateActionsCallbackInterfaces = new List<ICombateActions>();
    private readonly InputAction m_Combate_Ataque;
    public struct CombateActions
    {
        private @PlayerControls m_Wrapper;
        public CombateActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Ataque => m_Wrapper.m_Combate_Ataque;
        public InputActionMap Get() { return m_Wrapper.m_Combate; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CombateActions set) { return set.Get(); }
        public void AddCallbacks(ICombateActions instance)
        {
            if (instance == null || m_Wrapper.m_CombateActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CombateActionsCallbackInterfaces.Add(instance);
            @Ataque.started += instance.OnAtaque;
            @Ataque.performed += instance.OnAtaque;
            @Ataque.canceled += instance.OnAtaque;
        }

        private void UnregisterCallbacks(ICombateActions instance)
        {
            @Ataque.started -= instance.OnAtaque;
            @Ataque.performed -= instance.OnAtaque;
            @Ataque.canceled -= instance.OnAtaque;
        }

        public void RemoveCallbacks(ICombateActions instance)
        {
            if (m_Wrapper.m_CombateActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICombateActions instance)
        {
            foreach (var item in m_Wrapper.m_CombateActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CombateActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CombateActions @Combate => new CombateActions(this);
    public interface ICombateActions
    {
        void OnAtaque(InputAction.CallbackContext context);
    }
}
